- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Brew cask install applications
      homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items:
        - spectacle
        - google-chrome
        - firefox
        - iterm2
        - intellij-idea-ce
        - webstorm
        - atom
        - sublime-text
        - charles
        - slack
        - java
        - postman

    - name: Brew install or update preinstalled
      homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - node
        - git
        - docker
        - zsh
        - zsh-completions
        - wget
        - maven
        - vscode
        - npm
        - terraform

    - name: Install oh my zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    - name: Copy configured zshrc
      copy:
        src: ./zshrc
        dest: ~/.zshrc
